### ISSUE TITLE
爱迪德无法正常授权，过一断时间就要重新插回广电机。

### ISSUE THREAD

**Issue by wzbbstx** [nx111/oscam#13]
oscam配置文件里没有屏蔽授权。（从日志里好像写入授权的？）但最终过了一段时间，大概10天左右就要重新插回广电机。非常麻烦，麻烦请N大神看看，能否修正这个问题。万分感谢。
对了。本地是爱迪德版本是（Irdeto SC 58 version 21 revision 1, patch level e）
-----------------------------------------------------------------------------------------------------------------
1970/01/01 09:17:33 7C5BF7D0 r   (reader) CA_irdeto [irdeto] Deactivating card
1970/01/01 09:17:34 7C5BF7D0 r   (reader) CA_irdeto [irdeto] creating thread for device /dev/sci0
1970/01/01 09:17:34 7F5D68EA r   (reader) CA_irdeto [irdeto] Reader initialized (device=/dev/sci0, detect=cd, pll max=31.50 MHz, wanted mhz=5.25 MHz)
1970/01/01 09:17:34 7F5D68EA r   (reader) CA_irdeto [irdeto] Reader sci internal, detected box type: dm500
1970/01/01 09:17:34 7F5D68EA r   (reader) CA_irdeto [irdeto] card detected
1970/01/01 09:17:35 7F5D68EA r   (reader) CA_irdeto [internal] ATR: 3B 9F 21 0E 49 52 44 45 54 4F 20 41 43 53 20 56 35 2E 38 95 
1970/01/01 09:17:35 7F5D68EA r   (reader) CA_irdeto [internal] Init card protocol T14, FI=2, F=558, D=1, N=0
1970/01/01 09:17:35 7F5D68EA r   (reader) CA_irdeto [internal] Calculated work ETU is 106.29 us reader mhz = 525
1970/01/01 09:17:35 7F5D68EA r   (reader) CA_irdeto [internal] Buffers readed  0 bytes total time_us 75434
1970/01/01 09:17:35 7F5D68EA r   (reader) CA_irdeto [internal] PLL Reader: ATR Fsmax is 6 MHz, clocking card to 5.25 Mhz (nearest possible mhz specified reader->mhz)
1970/01/01 09:17:36 7F5D68EA r   (reader) CA_irdeto [internal] detect irdeto card
1970/01/01 09:17:36 7F5D68EA r   (reader) CA_irdeto [internal] Irdeto SC 58 version 21 revision 1, patch level e
1970/01/01 09:17:36 7F5D68EA r   (reader) CA_irdeto [internal] caid: 0606, acs: 0.05, country code: CHN
1970/01/01 09:17:37 7F5D68EA r   (reader) CA_irdeto [internal] providers: 4, ascii serial: ##########, hex serial: ######, hex base: ##
1970/01/01 09:17:39 7F5D68EA r   (reader) CA_irdeto [internal] WARNING: For Irdeto cards you will have to set 'mhz= 600' in oscam.server
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [internal] active providers: 4 (083dc4,000c00,ffffff,ffffff)
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [internal] found card system irdeto
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max alloted of 1
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] entitlements for provider: 1, id: 083DC4
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 7FFD, date: 2016/11/22 - 2016/12/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 7FFB, date: 2018/03/26 - 2018/04/05
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: FFD8, date: 2018/03/26 - 2018/04/05
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0001, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 007B, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0015, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0054, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 000C, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0045, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0002, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 000B, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0071, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0080, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 000F, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 001C, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0073, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 006E, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0075, date: 2017/04/13 - 2017/10/10
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0074, date: 2017/04/13 - 2017/10/10
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0076, date: 2017/04/13 - 2017/10/10
1970/01/01 09:17:40 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 0014, date: 2018/03/25 - 2018/09/22
1970/01/01 09:17:41 7F5D68EA r   (reader) CA_irdeto [irdeto] entitlements for provider: 2, id: 000C00
1970/01/01 09:17:41 7F5D68EA r   (reader) CA_irdeto [irdeto] chid: 000A, date: 2013/01/16 - 2013/02/15
-----------------------------------------------------------------------------------------------------------------
1970/01/01 09:00:39 63E31639 c      (ecm) VU+U4K_SE (0606@000000/0045/07D1/3C:99A2ABC58726A6BCF65BAF810090937A): found (236 ms) by CA_irdeto
1970/01/01 09:00:40 63E31639 c      (ecm) VU+U4K_SE (0606@000000/0045/2907/3C:9986AEDA01F9F4B7CBFE37D3436C8FB1): found (166 ms) by CA_irdeto
1970/01/01 09:00:44 7C5BF7D0 r   (reader) CA_irdeto [irdeto] VU+U4K_SE emmtype=global, len=12 (hex: 0x0C), cnt=0: written (56 ms)
1970/01/01 09:00:44 7C5BF7D0 r   (reader) CA_irdeto [irdeto] VU+U4K_SE emmtype=global, len=13 (hex: 0x0D), cnt=0: written (57 ms)
1970/01/01 09:00:55 63E31639 c      (ecm) VU+U4K_SE (0606@000000/0045/07D1/3C:777885760026FC445D8E496D17AA72BB): found (176 ms) by CA_irdeto
1970/01/01 09:00:56 63E31639 c      (ecm) VU+U4K_SE (0606@000000/0045/2907/3C:6F64E5F3187940BB5786A5A789958680): found (169 ms) by CA_irdeto
1970/01/01 09:01:11 63E31639 c      (ecm) VU+U4K_SE (0606@000000/0045/07D1/3C:722DCB650AAB720E832730876182EA5A): found (242 ms) by CA_irdeto

**Comment by wzgtvro** [comment]
使用newcamd协议即可正常授权
