### ISSUE TITLE
Does  ‘DVN boxkey’ tool still maintained ?

### ISSUE THREAD

**Issue by ihipop** [nx111/oscam#19]
![default](https://user-images.githubusercontent.com/423077/40597241-ccff950c-6272-11e8-8a58-081b5a74915e.png)
https://www.freedmx.net/forum.php?mod=viewthread&tid=1977

I want to get AuthorizeID of DVN，But could not work with this tool

If this tool is no longer maintained,Could you please tell me the contex character of AuthorizeID  so I can find it myself by hand ?
Many Thanks for your kindness.

**Comment by nx111** [comment]
Deplicated now.
