### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Screamfox** [nx111/oscam#21]
Please merge with the latest OScam-Emu Actual Version Emu r771, your version is deprecated.
I think your Oscam '' trunk '' miss some patch check in the web 👍 
And can you do a list in the Readme with your modification like (patch a8plusbox,  fixes made from you and etc... ) i think this can be help full to understand what is differents between your source code and the source code provided by streamboard and other patch like OScam-Emu, just say what you have added like patch and coding made by you. Can be very useful in case someone want to know if your OScam is very usefull cuz OSCam with a8plus patch probably is not really important in distributions like Ubuntu Debian and ... Codes from non original sources can give some affraid with people about backdoors and etc.. so please just do a list of coded strings made by you and the patch added in your OScam.
Not like the commits in github just a ''Resume'' about this.

Ex:.

- Oscam-Emu Patch r770 (latest 771 look in oscam-emu repo)
- a8plus patch 
- fix in a8plus patch (fixed blablablabla)
.
.
.
Thank you.
Rgds
David Martins  /Alias/  Screamfox

**Comment by nx111** [comment]
updated.
