### ISSUE TITLE
OSCAM EMU PATCH POWERVU HASHMODE CW:15 NEED FIX PLS

### ISSUE THREAD

**Issue by PAKO34** [nx111/oscam#24]
**OSCAM EMU PATCH POWERVU HASHMODE CW:15 NEED FIX PLS**

**Comment by nx111** [comment]
where is the patch?

**Comment by PAKO34** [comment]
pls fix this

`https://github.com/oscam-emu/oscam-emu/blob/master/oscam-emu.patch`

**Comment by Screamfox** [comment]
@PAKO34  why you don't open a tciket in oscam-emu they fix it !

**Comment by nx111** [comment]
Always merged it.

**Comment by nx111** [comment]
But it has no hash mode 15.

**Comment by PAKO34** [comment]
Screamfox they are very busy, they dont see my messages

**Comment by PAKO34** [comment]
nx11 we need sony packets and afn packets fix

`http://oi67.tinypic.com/2z3nw1v.jpg`
