### ISSUE TITLE
module-dvbapi.c:2587:23: error: expected ‘)’ before ‘;’ token

### ISSUE THREAD

**Issue by dgdell** [nx111/oscam#26]
N 大你好！，在编译 oscam 加 USE_STAPI=1函数时 出现下面错误，我尝试改了 fprintf(fp,"%c: %s",p->type,p->devname);可编译通过。这里"%c: %s";p->type 是手误还是赋值？ 

module-dvbapi.c: In function ‘dvbapi_write_prio’:
module-dvbapi.c:2587:23: error: expected ‘)’ before ‘;’ token
    fprintf(fp,"%c: %s";p->type,p->devname);

#ifdef WITH_STAPI
		if(p->type == 's'){
			fprintf(fp,"%c: %s";p->type,p->devname);
			if(p->pmtfile[0])
				fprintf(fp," %s",p->pmtfile);
			if(p->disablefilter)
				fprintf(fp," %d",p->disablefilter);
			fprintf(fp,"\n");
			continue;
		}
#endif

**Comment by nx111** [comment]
已修复。
