### ISSUE TITLE
 OpenWRT编译OSCAM 版本 显示问题

### ISSUE THREAD

**Issue by mymail6** [nx111/oscam#28]
通过 Git方式编译出来OSCAM  貌似版本 号码 ，都是_dd15e 的显示（例如：r11441_dd15e），但N大自己的编译的OS，版本显示都会有Oscam版本加 commit显示（例如：r11441_d8779）不知道这个是N大有意区分，还是BUG，请N大查看下！
![qq 20181224101812](https://user-images.githubusercontent.com/44636083/50389467-8d95b200-0765-11e9-9be9-3bac7977aca3.png)
![133](https://user-images.githubusercontent.com/44636083/50389519-4d82ff00-0766-11e9-955c-a745dd3a1228.png)

**Comment by nx111** [comment]
It's not a issue.

**Comment by nx111** [comment]
My build's version is:   <svn revision>_<commit id>

**Comment by nx111** [comment]
Your build script has bugs.
