### ISSUE TITLE
Ask for help my streamcard can not be decoded

### ISSUE THREAD

**Issue by zhangtvro** [nx111/oscam#31]
Can someone help me? The new version of the software can not be decoded. My  card caid  is  4AD2 。Below is my card reading log, configuration is no problem.
![image](https://user-images.githubusercontent.com/46662020/51786382-80be1100-219e-11e9-90f6-a10d53c7c319.png)

2019/01/26 17:13:16 367B4496 r   (reader) SMSX [internal] found card system streamguard
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max alloted of 1
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard] Provider:0005AA
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard] entitlements for provider: 0 (4AD2:0005AA)
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1007 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1008 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1009 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 100C auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 100E auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 102D auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 102E auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 102F auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1088 auth:2019-01-04 03:59:44  valid:2019-01-04 03:59:44 - 2020-02-05 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1030 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1031 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:16 367B4496 r   (reader) SMSX [streamguard]     chid: 1032 auth:2015-11-20 00:00:00  valid:2020-12-31 23:59:59 - 2020-12-31 23:59:59
2019/01/26 17:13:17 00000000 s     (main) init for all local cards done
2019/01/26 17:13:17 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
2019/01/26 17:13:17 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
2019/01/26 17:13:17 00000000 s (anticasc) anti cascading disabled
2019/01/26 17:13:17 1F96F11C c   (client) plain dvbapi-client granted (dvbapiau, au=auto (3 reader))
2019/01/26 17:13:17 1F96F11C c   (dvbapi) dvbapi channelcache loaded from /etc/tuxbox/config/oscam.ccache
2019/01/26 17:13:17 1F96F11C c   (dvbapi) Detected /dev/dvb/adapter0/demux0 Api: 0, userconfig boxtype: 1 maximum amount of possible filters is 32 (oscam limit is 32)
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0606 ECM_PID: 08BC PROVID: 000000 
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AD2 ECM_PID: 08BD PROVID: 000000 
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 found 2 ECMpids and 2 STREAMpids in caPMT
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 1 
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4AD2 PROVID 000000 ECMPID 08BD ANY CHID PMTPID 08B0 VPID 08B1
2019/01/26 17:13:20 1F96F11C c   (dvbapi) Demuxer 0 found 2 ECMpids and 2 STREAMpids in PMT
2019/01/26 17:13:20 1F96F11C c      (ecm) dvbapiau (4AD2@000000/66B3/01FC/7C:942E3A9AC9CF7C20E2E7C39453B5971B): found (225 ms) by SMSX
2019/01/26 17:13:23 5E303AC3 h    (webif) all debug_level=16
2019/01/26 17:13:25 367B4496 r ECM: 81 30 79 00 05 AA 66 A5 5C 4C 25 CE FA 01 56 9F 0E BF A0 35 A7 E2 7A 12 A6 72 50 82 9C B8 8F D8 49 93 DD 5C 84 58 D7 FF F5 DD 5D 92 50 CE 19 C1 32 4C 52 03 DF C9 C9 F5 B2 66 53 8C 6D E8 FE 42 34 51 64 51 C2 C6 7B CC 00 9D 71 69 A0 F1 FB AB 38 FD E4 F4 E5 82 1F 8A 3D 29 D6 AA 51 FF F9 C3 8B DD 59 4C 07 04 DB 22 10 6B 2F 36 E5 6C 23 DE 76 63 65 0C AB 23 35 54 80 BB 73 18 
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 1 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:25 367B4496 r   (reader)   80 32 00 00 7C 
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 00000000   >> OSCam <<  cardserver log switched, version 1.20_svn, build r11486 (arm-unknown-linux-gnueabihf-libusb)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 124 bytes, expected len 2 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:25 367B4496 r   (reader)   81 30 79 00 05 AA 66 A5 5C 4C 25 CE FA 01 56 9F 
2019/01/26 17:13:25 367B4496 r   (reader)   0E BF A0 35 A7 E2 7A 12 A6 72 50 82 9C B8 8F D8 
2019/01/26 17:13:25 367B4496 r   (reader)   49 93 DD 5C 84 58 D7 FF F5 DD 5D 92 50 CE 19 C1 
2019/01/26 17:13:25 367B4496 r   (reader)   32 4C 52 03 DF C9 C9 F5 B2 66 53 8C 6D E8 FE 42 
2019/01/26 17:13:25 367B4496 r   (reader)   34 51 64 51 C2 C6 7B CC 00 9D 71 69 A0 F1 FB AB 
2019/01/26 17:13:25 367B4496 r   (reader)   38 FD E4 F4 E5 82 1F 8A 3D 29 D6 AA 51 FF F9 C3 
2019/01/26 17:13:25 367B4496 r   (reader)   8B DD 59 4C 07 04 DB 22 10 6B 2F 36 E5 6C 23 DE 
2019/01/26 17:13:25 367B4496 r   (reader)   76 63 65 0C AB 23 35 54 80 BB 73 18 
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 45 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:25 367B4496 r   (reader)   00 C0 00 00 2A 
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 42 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:25 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:25 1F96F11C c      (ecm) dvbapiau (4AD2@000000/66A5/01FC/7C:FAE96191231BE8EAC95083D0712A1A1F): found (226 ms) by SMSX
2019/01/26 17:13:25 5E303AC3 h    (webif) all debug_level=24
2019/01/26 17:13:35 367B4496 r ECM: 80 30 79 00 05 AA 66 B9 5C 4C 25 D3 14 C9 04 15 56 B8 82 42 9D 9D 44 32 EE B3 A8 B3 12 5D 9F 83 51 97 C7 9E CB F2 A8 97 B9 0F C8 6E BD 29 4F 5E BC A6 B0 8E 43 1E EC 1E 97 C7 80 11 F3 AD 24 F4 BD 75 AC 91 25 DC 94 AC 64 A8 06 AA F9 14 17 01 96 0F 3F 96 CA 87 7B 77 91 F6 71 49 67 1E 0E 6D 45 F3 BE A4 B0 8E FC B7 82 99 06 83 E7 D4 EB B3 31 E0 8C 34 DE D6 AB 86 E1 41 00 A4 
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 1 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:35 367B4496 r   (reader)   80 32 00 00 7C 
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 124 bytes, expected len 2 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:35 367B4496 r   (reader)   80 30 79 00 05 AA 66 B9 5C 4C 25 D3 14 C9 04 15 
2019/01/26 17:13:35 367B4496 r   (reader)   56 B8 82 42 9D 9D 44 32 EE B3 A8 B3 12 5D 9F 83 
2019/01/26 17:13:35 367B4496 r   (reader)   51 97 C7 9E CB F2 A8 97 B9 0F C8 6E BD 29 4F 5E 
2019/01/26 17:13:35 367B4496 r   (reader)   BC A6 B0 8E 43 1E EC 1E 97 C7 80 11 F3 AD 24 F4 
2019/01/26 17:13:35 367B4496 r   (reader)   BD 75 AC 91 25 DC 94 AC 64 A8 06 AA F9 14 17 01 
2019/01/26 17:13:35 367B4496 r   (reader)   96 0F 3F 96 CA 87 7B 77 91 F6 71 49 67 1E 0E 6D 
2019/01/26 17:13:35 367B4496 r   (reader)   45 F3 BE A4 B0 8E FC B7 82 99 06 83 E7 D4 EB B3 
2019/01/26 17:13:35 367B4496 r   (reader)   31 E0 8C 34 DE D6 AB 86 E1 41 00 A4 
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 45 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:35 367B4496 r   (reader)   00 C0 00 00 2A 
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 42 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:35 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:35 1F96F11C c      (ecm) dvbapiau (4AD2@000000/66B9/01FC/7C:7CC5772C7B65CDAA970D333706C5E63B): found (227 ms) by SMSX
2019/01/26 17:13:45 367B4496 r ECM: 81 30 79 00 05 AA 66 AD 5C 4C 25 DE 48 F2 47 4E AD 48 D8 63 91 9C F7 2C C6 12 21 88 84 63 04 80 A1 4D 41 9E CC 81 E9 A9 9B 7F 6D 87 09 B8 20 41 7A 26 FE 9E 09 22 65 C8 8A 9A 0B A2 AC 88 47 A6 EA AF 63 21 03 D0 6C 4B 0A C4 E3 80 EF 93 64 5A CB 85 D5 C9 2E 8E A6 1E 74 BB 3F 22 04 42 6F C6 3C 44 D4 50 E7 BD 0A EA A1 5A BD 81 E8 13 4F 69 C0 03 CD 1D 48 9C 98 B0 5E 0A E1 E4 
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 1 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:45 367B4496 r   (reader)   80 32 00 00 7C 
2019/01/26 17:13:45 00000000   >> OSCam <<  cardserver log switched, version 1.20_svn, build r11486 (arm-unknown-linux-gnueabihf-libusb)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 124 bytes, expected len 2 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:45 367B4496 r   (reader)   81 30 79 00 05 AA 66 AD 5C 4C 25 DE 48 F2 47 4E 
2019/01/26 17:13:45 367B4496 r   (reader)   AD 48 D8 63 91 9C F7 2C C6 12 21 88 84 63 04 80 
2019/01/26 17:13:45 367B4496 r   (reader)   A1 4D 41 9E CC 81 E9 A9 9B 7F 6D 87 09 B8 20 41 
2019/01/26 17:13:45 367B4496 r   (reader)   7A 26 FE 9E 09 22 65 C8 8A 9A 0B A2 AC 88 47 A6 
2019/01/26 17:13:45 367B4496 r   (reader)   EA AF 63 21 03 D0 6C 4B 0A C4 E3 80 EF 93 64 5A 
2019/01/26 17:13:45 367B4496 r   (reader)   CB 85 D5 C9 2E 8E A6 1E 74 BB 3F 22 04 42 6F C6 
2019/01/26 17:13:45 367B4496 r   (reader)   3C 44 D4 50 E7 BD 0A EA A1 5A BD 81 E8 13 4F 69 
2019/01/26 17:13:45 367B4496 r   (reader)   C0 03 CD 1D 48 9C 98 B0 5E 0A E1 E4 
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 45 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:45 367B4496 r   (reader)   00 C0 00 00 2A 
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 42 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:45 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:45 1F96F11C c      (ecm) dvbapiau (4AD2@000000/66AD/01FC/7C:A57881AD3375E2BC947B7EA97DDD70CF): found (227 ms) by SMSX
2019/01/26 17:13:55 367B4496 r ECM: 80 30 79 00 05 AA 66 B5 5C 4C 25 E8 0A D4 6A D8 D4 25 35 4E 91 9C F7 2C C6 12 21 88 60 F9 B8 B2 49 9C A4 ED DF 37 E4 5F EA 53 0A B0 80 CA A6 3D D4 BD 16 19 11 28 17 46 24 03 88 F8 91 4E 43 0C AF D1 D0 BC F2 5B AD 61 2E 3F 39 9E 3E 99 CB B0 95 65 33 54 68 EA E9 12 44 E2 AB 63 21 28 C5 8A 10 17 9F 8F 51 4A AA 65 5E 9D 0A F2 3A 9E 03 6A 9C A7 EC 02 80 DB BF 6E 6C 6F 35 C9 
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 1 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:55 367B4496 r   (reader)   80 32 00 00 7C 
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 124 bytes, expected len 2 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:55 367B4496 r   (reader)   80 30 79 00 05 AA 66 B5 5C 4C 25 E8 0A D4 6A D8 
2019/01/26 17:13:55 367B4496 r   (reader)   D4 25 35 4E 91 9C F7 2C C6 12 21 88 60 F9 B8 B2 
2019/01/26 17:13:55 367B4496 r   (reader)   49 9C A4 ED DF 37 E4 5F EA 53 0A B0 80 CA A6 3D 
2019/01/26 17:13:55 367B4496 r   (reader)   D4 BD 16 19 11 28 17 46 24 03 88 F8 91 4E 43 0C 
2019/01/26 17:13:55 367B4496 r   (reader)   AF D1 D0 BC F2 5B AD 61 2E 3F 39 9E 3E 99 CB B0 
2019/01/26 17:13:55 367B4496 r   (reader)   95 65 33 54 68 EA E9 12 44 E2 AB 63 21 28 C5 8A 
2019/01/26 17:13:55 367B4496 r   (reader)   10 17 9F 8F 51 4A AA 65 5E 9D 0A F2 3A 9E 03 6A 
2019/01/26 17:13:55 367B4496 r   (reader)   9C A7 EC 02 80 DB BF 6E 6C 6F 35 C9 
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 12 ETU (992 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit size 5 bytes, expected len 45 bytes, delay 0 us, timeout=992 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit:
2019/01/26 17:13:55 367B4496 r   (reader)   00 C0 00 00 2A 
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Transmit succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 42 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Setting timeout to 9600 ETU (793600 us)
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive size 1 bytes, delay 0 us, timeout=793600 us
2019/01/26 17:13:55 367B4496 r   (reader) SMSX [streamguard] IFD: Receive succesful
2019/01/26 17:13:55 1F96F11C c      (ecm) dvbapiau (4AD2@000000/66B5/01FC/7C:EC9AED33AEE7DA934B007586EBC4DCDC): found (227 ms) by SMSX

**Comment by nx111** [comment]
build 20181224 (r11443) working ?

**Comment by zhangtvro** [comment]
Similarly, oscam r11443  can't work.  oscam 11380  works well。

**Comment by zhangtvro** [comment]
Dear NX111, I have a request that oscam in your disk cannot work on my device. Can you cancel the PCSC Driver compilation?

**Comment by nx111** [comment]
please post the full logs and your config to me. (gd.zhangdz@gmail.com)

**Comment by nx111** [comment]
weixin: 381481281

**Comment by ohmza** [comment]
Sorry for digging this thread, but I kind of want to know how do you get the BOXID value in order to make the oscam works properly.

**Comment by robiul0011** [comment]
> [streamguard]

hello 👋 broo my need to [streamguard] support oscam please share
