### ISSUE TITLE
11588版本，天柏不能读卡了！

### ISSUE THREAD

**Issue by suqianstone** [nx111/oscam#32]
11588版本，天柏不能读卡了......不但不能解码了。连授权都不见了。。。。。。。

**Comment by nx111** [comment]
最近的上游代码变化较大，导致合并有问题。正在修复中。

**Comment by nx111** [comment]
已重新编译上传。

**Comment by kongjun0** [comment]
11488今天下载还不能读天柏卡，BOXKEY也无法输入，请修改下BUG，用源码编译也同样不能4A30
