### ISSUE TITLE
11488不能读天柏卡，BOXKEY也无法输入，请修改下BUG，用源码编译也同样不能4A30

### ISSUE THREAD

**Issue by kongjun0** [nx111/oscam#33]
11488今天下载还不能读天柏卡，BOXKEY也无法输入，请修改下BUG，用源码编译也同样不能4A30

**Comment by kongjun0** [comment]
另外ow的makefile能提供吗

**Comment by nx111** [comment]
经验证，可以输入boxkey。请确保boxkey格式和长度正确。dvn的boxkey长度为64位十六进制字符（32字节），中间不能有空格等其他字符。
