### ISSUE TITLE
11508版本没有smargo协议，i686版本不能请求DVB API解密

### ISSUE THREAD

**Issue by kongjun0** [nx111/oscam#34]
11508版本没有smargo协议，在LIUNX下安装i686版本不能请求DVB API解密，请修复。

**Comment by jack2015** [comment]
config.h  去掉下面的 "//"  或者  make config  配置 smago 使能
//#define CARDREADER_SMARGO 1

**Comment by jack2015** [comment]
config.h 去掉下面的 "//" 或者 make config 配置 smargo 使能
//#define CARDREADER_SMARGO 1

**Comment by kongjun0** [comment]
那么关于后面的版本，Tvheadend使用DVBAPI。  oscam不请求解密信息，能否修复下，11390版本这个功能都正常，11451到11508都不能使用DVBAPI,就是不解密

**Comment by nx111** [comment]
fixed.
