### ISSUE TITLE
r11532_881e3版DVN不能解密.

### ISSUE THREAD

**Issue by xiaole51** [nx111/oscam#36]
一直在用r11424_79048版一切正常,今天想试试新版换上后无法解密.

测试版本: oscam-dm800-r11532_881e3-pcsc-ssl-inline-nx111-20190721
现象: 读卡正常,授权信息可读出但是不可解密.
log信息如下:

还有一个问题:
请教A8P版如何使用呢?在A8P设备上无法解密.
播放器根本没有跟socam通信.有何窍门吗?

`2019/07/21 22:49:53 1A50C039 r (reader) reader0 [dvn] cardreader_do_checkhealth: reader->card_status = 2, ret = 1 
2019/07/21 22:49:53 00000000 (work) start reader thread action 13 
2019/07/21 22:49:53 00000000 (main) starting thread client work 
2019/07/21 22:49:53 00000000 (main) client work thread started 
2019/07/21 22:49:53 1A50C039 r (work) data from add_job action=13 client r reader0 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) New events occurred on 1 of 4 handlers after 698 ms inactivity 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) Now handling fd 17 that reported event 3 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) Received: 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) 42 F0 0C 00 35 FB 00 00 00 01 FF 22 A8 21 0D 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) Demuxer 0 filter3[0] = 42, filter mask[0] = FF, flt&mask = 42 , buffer[0] = 42, buffer[0] & mask = 42 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) Demuxer 0 Filter 3 fetched SDT data (length = 0x00F): 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) 42 F0 0C 00 35 FB 00 00 00 01 FF 22 A8 21 0D 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) sdt-info dbg: sdt data: 
2019/07/21 22:49:53 1AA2A5FA c (dvbapi) 42 F0 0C 00 35 FB 00 00 00 01 FF 22 A8 21 0D 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) New events occurred on 1 of 4 handlers after 167 ms inactivity 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Now handling fd 10 that reported event 11 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 stop filter 1 try 1 (fd: 10 api: 0, caid: 4A30, provid: 000000, ecmpid: 1202) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 flushing stale input data of filter 1 (fd:10) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 has 2 ecmpids, 2 streampids, 0 ecmfilters and 0 of max 63 emmfilters 
2019/07/21 22:49:54 1AA2A5FA c (chk) caid 4A02 not found in caidlist reader reader0 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 ignore ecmpid 0 4A02@000000:1102:10000 (no matching reader) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 prio ecmpid 1 4A30@000000:1202:151C weight: 1 (1 local and 0 cacheex readers) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 prio ecmpid 1 4A30@000000:1202 weight: 2 (found caid/provid in cache) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 sorting the ecmpids took 5 ms 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 try to start new filter for caid: 4A30, provid: 000000, pid: 1202 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Open device /dev/dvb/adapter0/demux0 (fd 10) 
2019/07/21 22:49:54 1AA2A5FA c (dvbapi) Demuxer 0 Filter 1 started successfully (caid 4A30 provid 000000 pid 1202) 
2019/07/21 22:49:54 7D24332E h (main) starting thread webif workthread 
2019/07/21 22:49:54 7D24332E h (main) webif workthread thread started 
2019/07/21 22:49:54 7D24332E h (webif) WebIf: Origin checked. Result: access from 192.168.1.31 => allowed 
2019/07/21 22:49:54 7D24332E h (webif) all debug_level=0 
2019/07/21 22:49:57 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 12 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:49:57 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:00 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:00 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:03 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:03 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:06 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 13 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:06 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:09 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:09 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:12 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:12 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1202 ANY CHID PMTPID 0401 VPID 00A1 
2019/07/21 22:50:13 1AA2A5FA c (dvbapi) Demuxer 0 stopped descrambling for program 14B6 (4A02@000000:14B6 unknown) 
2019/07/21 22:50:14 1AA2A5FA c (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A02 ECM_PID: 1104 PROVID: 000000 
2019/07/21 22:50:14 1AA2A5FA c (dvbapi) Demuxer 0 ecmpid 1 CAID: 4A30 ECM_PID: 1204 PROVID: 000000 
2019/07/21 22:50:14 1AA2A5FA c (dvbapi) Demuxer 0 found 2 ECMpids and 2 STREAMpids in caPMT 
2019/07/21 22:50:14 1AA2A5FA c (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 1 
2019/07/21 22:50:14 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:15 1AA2A5FA c (dvbapi) Demuxer 0 found 2 ECMpids and 2 STREAMpids in PMT 
2019/07/21 22:50:17 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:17 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:20 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:20 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:23 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 12 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:23 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:26 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:26 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:29 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:29 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:32 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:32 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:35 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:35 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:38 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:38 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:41 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 13 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:41 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:44 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:44 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:47 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:47 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:50 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 12 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:50 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:53 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:53 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:56 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:56 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:50:56 00000000 >> OSCam << cardserver log switched, version 1.20_svn, build r11532_881e3 (mipsel-unknown-linux-gnu) 
2019/07/21 22:50:59 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:50:59 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:03 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 13 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:03 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:06 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:06 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:09 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:09 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:12 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 13 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:12 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:15 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 12 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:15 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:18 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:18 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:21 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:21 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:24 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 14 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:24 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:27 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:27 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:30 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:30 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:33 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 12 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:33 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:36 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:36 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:39 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:39 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:42 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:42 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:45 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 14 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:45 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:48 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:48 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:51 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:51 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:54 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 14 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:54 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:51:57 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:51:57 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:00 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:00 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:03 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 13 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:03 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:06 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:06 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:09 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:09 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:12 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:12 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:15 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:15 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:18 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:18 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:21 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 10 ms with 1 enabled and 1 disabled ecmpids! 
2019/07/21 22:52:21 1AA2A5FA c (dvbapi) Demuxer 0 trying to descramble PID 1 CAID 4A30 PROVID 000000 ECMPID 1204 ANY CHID PMTPID 0403 VPID 00A3 
2019/07/21 22:52:24 1AA2A5FA c (dvbapi) Demuxer 0 restarting decoding requests after 11 ms with 1 enabled and 1 disabled ecmpids! `

**Comment by nx111** [comment]
请再试试前最近的几个版本，看看是那个版本开始出问题。

**Comment by nx111** [comment]
试试最新版本，已修复之前的一处合并错误。

**Comment by xiaole51** [comment]
马上编译了一个,可以解DVN了.
logs:
https://pastebin.com/raw/ULAy0eue

还有一个问题是从某一版开始本机api解密一条记录会跟随两条cache记录.有办法关闭吗?
客户机解密没有这现象.log中的tvhead是客户机.

2019/07/28 11:37:43 1654E1D1 c      (ecm) linuxsatsupport (4A30@000000/1520/1967/90:5B7D5BBC749F32CAB46B04069004547B): found (131 ms) by reader0 - 求索生活高清
2019/07/28 11:37:43 1654E1D1 c      (ecm) linuxsatsupport (4A30@000000/1520/1967/90:5B7D5BBC749F32CAB46B04069004547B): cache2 (38 ms) by reader0 - 求索生活高清
2019/07/28 11:37:43 1654E1D1 c      (ecm) linuxsatsupport (4A30@000000/1520/1967/90:5B7D5BBC749F32CAB46B04069004547B): cache2 (1 ms) by reader0 - 求索生活高清

**Comment by nx111** [comment]
dvbapi 对ecm请求进行了优化，显示cache记录是正常的，没有必要屏蔽其log。
