### ISSUE TITLE
DM500设备无法使用20190130开始编译的oscam文件，20190110及以前的可以运行！

### ISSUE THREAD

**Issue by wzbbstx** [nx111/oscam#38]
DM500设备无法使用20190130开始编译的oscam文件，20190110及以前的可以正常运行！
请NX111大神修复一下。
20190130开始编译的oscam文件---错误提示：
error while loading shared libraries:librt.so.1:cannot open shared object file:no such file or directory

-------------------------
oscam百度网盘上NX111上下载的（https://pan.baidu.com/s/1qXOaw6w?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2Fsharelink1697622392-259438295227075%2Foscam%2FOLD&parentPath=%2Fsharelink1697622392-259438295227075）

**Comment by nx111** [comment]
fixed.
