### ISSUE TITLE
(newcamd) expected MSG_CLIENT_2_SERVER_LOGIN_ACK (E1), received FF (using CCcam.cfg native)

### ISSUE THREAD

**Issue by RetroDev81** [nx111/oscam#4]
Hello, I am using the option of the native CCcam.cfg to read Clines and Nlines, but  Nlines does not read them correctly, it seems that there is a problem with the reading of the ncd_key, the key does not recognize it and the mark as 000000000000000 in webif .

Please, if you can fix it, it would be quite a detail on your part.

Thank you

**Comment by nx111** [comment]
fixed.
