### ISSUE TITLE
同方3.2 CAID识别奇怪现象.

### ISSUE THREAD

**Issue by xiaole51** [nx111/oscam#43]
近日遇见同方卡奇怪现象,烦请N大过目.

卡片信息:
收视卡为同方3.2版.无机卡绑定.
在广电盒子能正常解密.
OScam官方版和N大的修改版均识别到CAID为CA02.
N大版可读取授权信息.

异常现象:
但是Demuxer中并无CA02存在.
因此无法正确获取密钥.

2020/01/08 21:53:31 7D88C82B c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 1031 PROVID: 000000 
2020/01/08 21:53:31 7D88C82B c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4A0E ECM_PID: 1131 PROVID: 000000 
2020/01/08 21:53:31 7D88C82B c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 4AD3 ECM_PID: 123F PROVID: 000000 

官方版的log中看似已得到正确密钥,但是实际无法解密出画面.
并且是以CA0E获取的密钥.固然无法解密.

2020/01/08 21:39:26 0F805032 c      (ecm) dvbapiau (4A0E@000000/6000/0B55/9B:60C72C4B5065F6C6939678D01ED0F032): found (203 ms) by NKYX
2020/01/08 21:39:35 0F805032 c      (ecm) dvbapiau (4A0E@000000/6000/0B55/9B:7A1FAC6DFD100F383924143027688B65): found (202 ms) by NKYX
2020/01/08 21:39:55 0F805032 c      (ecm) dvbapiau (4A0E@000000/6000/0B55/9B:38D74D444D7D37E536DB5B21625DA591): found (202 ms) by NKYX

疑问:
卡片的CAID在当前有线网中并无存在.
但是在广电盒子内可正常解密.
Oscam识别到的CAID与卡的实际CAID有无可能不对应?
如果上面一条不成立.可否修改oscam源码将CAID强制指定到DA0E后正确获取密钥?

烦请N大指明方向.

两个版本Log附上.

官版log
 [OSCam r11505_log](https://pastebin.com/6fLZ4yzt)

N大版log
[OSCam r11572_71e56_log](https://pastebin.com/U4cid2fF)

**Comment by nx111** [comment]
目前不支持更高版本的TF卡片。
