### ISSUE TITLE
PCSC读卡DVN变为 card system not supported

### ISSUE THREAD

**Issue by xiaole51** [nx111/oscam#47]
PCSC读卡DVN变为 card system not supported
下载早期的19/08月版本同样问题.
应该是PCSC读卡方式的问题了.

PS: ATR 末尾已删除.

9:43:41 00000000 s >> OSCam << cardserver log switched, version 1.20_svn, build r11603_cfec5 (x86_64-linux-gnu-ssl-libusb-pcsc)
09:43:41 00000000 s     (main) System name    = Linux
09:43:41 00000000 s     (main) Host name      = ubuntu
09:43:41 00000000 s     (main) Release        = 4.4.0-142-generic
09:43:41 00000000 s     (main) Version        = #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
09:43:41 00000000 s     (main) Machine        = x86_64
09:43:41 00000000 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 3612
09:43:41 00000000 s      (emu) OSCam-Emu version 789
09:43:41 00000000 s     (main) signal handling initialized
09:43:41 00000000 s   (reader) emulator [emu] creating thread for device emulator
09:43:41 00000000 s   (reader) Reader-1 [pcsc] creating thread for device 0
09:43:41 00000000 s     (main) waiting for local card init
09:43:41 4230CD24 r      (emu) Stream key delayer initialized
09:43:41 4230CD24 r      (emu) Stream relay server initialized
09:43:41 4230CD24 r   (reader) emulator [emu] Reader initialized (device=emulator, detect=cd, mhz=357, cardmhz=357)
09:43:41 00000000        (emu) INFO: FFDecsa parallel mode = 128
09:43:41 14DDE33B r   (reader) Reader-1 [pcsc] Reader initialized (device=0, detect=cd, mhz=357, cardmhz=450)
09:43:41 30A306E2 h    (webif) webif: decompressed 185927 bytes back into 461904 bytes
09:43:41 30A306E2 h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
09:43:42 4230CD24 r   (reader) emulator [emu] card detected
09:43:43 14DDE33B r   (reader) Reader-1 [pcsc] PCSC was opened with handle: 1045960729
09:43:43 14DDE33B r   (reader) Reader-1 [pcsc] card detected
09:43:43 4230CD24 r   (reader) emulator [emu] found card system emu
09:43:43 4230CD24 r   (reader) emulator [emu] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max allotted of 1
09:43:43 4230CD24 r      (emu) Key file not found in: /usr/local/etc
09:43:43 4230CD24 r      (emu) Cannot open key file path: /var/keys
09:43:43 4230CD24 r      (emu) Total keys in memory: W:0 V:0 N:0 I:0 S:0 F:0 P:0 D:0 T:0 A:0
09:43:43 14DDE33B r   (reader) Reader-1 [pcsc] ATR: 3B 7F 12 00 00 44 56 4E 20 54 45  
09:43:44 14DDE33B r   (reader) Reader-1 [pcsc] DVN Jetcas version 4.0 card detect
09:43:45 14DDE33B r   (reader) Reader-1 [pcsc] card system not supported
09:43:45 14DDE33B r   (reader) Reader-1 [pcsc] Normal mode failed, reverting to Deprecated Mode
09:43:46 14DDE33B r   (reader) Reader-1 [pcsc] ATR: 3B 7F 12 00 00 44 56 4E 20 54 45 
09:43:47 14DDE33B r   (reader) Reader-1 [pcsc] DVN Jetcas version 4.0 card detect
09:43:48 14DDE33B r   (reader) Reader-1 [pcsc] card system not supported
09:43:48 14DDE33B r   (reader) Reader-1 [pcsc] THIS WAS A FAILED START ATTEMPT No 1 out of max allotted of 1
09:43:48 14DDE33B r   (reader) Reader-1 [pcsc] card initializing error
09:43:49 00000000 s     (main) init for all local cards done
09:43:49 00000000 s (emmcache) loading emmcache disabled since no reader is using it!

**Comment by nx111** [comment]
19年7月版本正常否？

**Comment by nx111** [comment]
不一定是pcsc读卡的问题，也可能是代码目前不支持该卡片，卡片初始化失败，也会这样显示。
