### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by iptvfta** [nx111/oscam#48]
closed

**Comment by SambasOnFire** [comment]
without pairing data of your stb, forget and I saw get_commkey_cmd, card now reply with 0x10 bytes maybe now use 3des and not des...

**Comment by iptvfta** [comment]
> without pairing data of your stb, forget and I saw get_commkey_cmd, card now reply with 0x10 bytes maybe now use 3des and not des...

how to get 3des

**Comment by dida8311** [comment]
how to get 3des
